# Generated by Django 3.2 on 2021-04-24 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shito.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Бытовая электроника', 'Бытовая электроника'), ('Готовый бизнес и оборудование', 'Готовый бизнес и оборудование'), ('Работа', 'Работа'), ('Для дома и дачи', 'Для дома и дачи'), ('Личные вещи', 'Личные вещи'), ('Животные', 'Животные'), ('Услуги', 'Услуги'), ('Недвижимость', 'Недвижимость'), ('Транспорт', 'Транспорт')], default='Транспорт', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('tel_number', models.IntegerField(blank=True, verbose_name='Telephone number')),
                ('avatar', models.ImageField(upload_to=shito.models.user_avatar_path)),
                ('city', models.TextField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300, verbose_name='Название')),
                ('descpition', models.TextField(blank=True, max_length=1000)),
                ('image', models.ImageField(upload_to=shito.models.user_directory_path)),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_edit', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Избранное')),
            ],
        ),
    ]
