# Generated by Django 3.2 on 2021-04-29 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shito', '0002_auto_20210424_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shito.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('Личные вещи', 'Личные вещи'), ('Бытовая электроника', 'Бытовая электроника'), ('Готовый бизнес и оборудование', 'Готовый бизнес и оборудование'), ('Услуги', 'Услуги'), ('Недвижимость', 'Недвижимость'), ('Животные', 'Животные'), ('Для дома и дачи', 'Для дома и дачи'), ('Транспорт', 'Транспорт'), ('Работа', 'Работа')], default='Транспорт', max_length=50),
        ),
    ]
