# Generated by Django 3.2 on 2021-05-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shito', '0004_alter_category_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('Недвижимость', 'Недвижимость'), ('Работа', 'Работа'), ('Животные', 'Животные'), ('Транспорт', 'Транспорт'), ('Личные вещи', 'Личные вещи'), ('Готовый бизнес и оборудование', 'Готовый бизнес и оборудование'), ('Для дома и дачи', 'Для дома и дачи'), ('Услуги', 'Услуги'), ('Бытовая электроника', 'Бытовая электроника')], default='Транспорт', max_length=50),
        ),
    ]
