# Generated by Django 3.2 on 2021-05-01 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shito', '0005_alter_category_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='favorites',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='shito.Ad', verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('Бытовая электроника', 'Бытовая электроника'), ('Недвижимость', 'Недвижимость'), ('Личные вещи', 'Личные вещи'), ('Услуги', 'Услуги'), ('Для дома и дачи', 'Для дома и дачи'), ('Транспорт', 'Транспорт'), ('Готовый бизнес и оборудование', 'Готовый бизнес и оборудование'), ('Животные', 'Животные'), ('Работа', 'Работа')], default='Транспорт', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
