# Generated by Django 3.2 on 2021-05-01 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shito', '0006_auto_20210501_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('Транспорт', 'Транспорт'), ('Личные вещи', 'Личные вещи'), ('Для дома и дачи', 'Для дома и дачи'), ('Готовый бизнес и оборудование', 'Готовый бизнес и оборудование'), ('Бытовая электроника', 'Бытовая электроника'), ('Услуги', 'Услуги'), ('Недвижимость', 'Недвижимость'), ('Животные', 'Животные'), ('Работа', 'Работа')], default='Транспорт', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_favorites', to='shito.Ad', verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
