# Generated by Django 3.2 on 2021-05-01 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shito', '0007_auto_20210501_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('Животные', 'Животные'), ('Личные вещи', 'Личные вещи'), ('Работа', 'Работа'), ('Транспорт', 'Транспорт'), ('Готовый бизнес и оборудование', 'Готовый бизнес и оборудование'), ('Бытовая электроника', 'Бытовая электроника'), ('Недвижимость', 'Недвижимость'), ('Услуги', 'Услуги'), ('Для дома и дачи', 'Для дома и дачи')], default='Транспорт', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='users_favorites', to='shito.Ad', verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
